### ISSUE TITLE
Acquire neuron models from the Allen Cell Types Database

### ISSUE THREAD

**Issue by eroma2014** [apache/airavata-cerebrum#17]
Allen Cell types database is https://celltypes.brain-map.org/data 
The current task will focus on four neuron types: 3 inhibitory ( SSt, PValb, ViP), 1 excitatory ( Scnn1a). 

### Tasks
- [x] Create a python module to query the Cell Types database using Allen SDK
- [x] Functionality to filter cell types, models and model properties
- [x] Create a template for the complete workflow from acquisition to build-network
- [x] Save the query description and its parameters 
    - [x] Ability to modify the query description and/or parameters and re-run the workflow

Git repo: https://github.com/srirampc/airavata-cerebrum/tree/main/airavata_cerebrum

**Comment by eroma2014** [comment]
The second and third tasks are completed by Sriram. Waiting for the project to be Public for status updates. The last task is about 95% completed and currently being worked on.

**Comment by srirampc** [comment]
The pull request #23 completes all the tasks of these issues.
