### ISSUE TITLE
Acquire the neuron population ratios from brain single cell atlases

### ISSUE THREAD

**Issue by eroma2014** [apache/airavata-cerebrum#18]
Map the neuron types between the cell types of BICN.  We focus on the datbase : https://alleninstitute.github.io/abc_atlas_access/intro.html and the four cell types : SSt, Pvalb, Vip, and one of excitatory type

### Tasks

- [x] Obtain Cell type ratios from BICN Al merfish atlas
- [x] Filter based on the layer and neuron types
- [x] Save the query description that enables modification and re-runs

Git repo: https://github.com/srirampc/airavata-cerebrum/tree/main/airavata_cerebrum

**Comment by eroma2014** [comment]
https://github.com/apache/airavata-cerebrum/issues/17, and this is being worked on in parallel.

**Comment by srirampc** [comment]
The pull request #23 completes all the tasks of this issue.
