### ISSUE TITLE
Acquire the synaptic probabilities from synaptic physiology database

### ISSUE THREAD

**Issue by eroma2014** [apache/airavata-cerebrum#19]
Synaptic physiology database : https://portal.brain-map.org/explore/connectivity/synaptic-physiology/synaptic-physiology-experiment-methods 

### Tasks

- [x] Use aisynphys library to acquire data
- [x] Filter based on the interaction neuron types
- [x] Save the query description that enables modification and re-runs

Git repo: https://github.com/srirampc/airavata-cerebrum/tree/main/airavata_cerebrum

**Comment by srirampc** [comment]
Currently working on this task

**Comment by srirampc** [comment]
The functionality is added in pull request #24
